# NOTE : A Dockerfile is for FRONTEND DEVELOPMENT environment

FROM node:18.12.1-bullseye

# Install useful tools
RUN apt-get update && apt-get install -y \
	apt-transport-https \
	htop \
	iproute2 \
	less \
	man-db \
	manpages-dev \
	net-tools \
	tree \
	vim \
	locales \
	&& echo "set nu\nsyntax on\nset mouse=a\nset shiftwidth=4\nset tabstop=4\nset enc=utf-8" > /root/.vimrc

# Set locales, timezone & Install oh-my-bash
RUN echo "en_US.UTF-8 UTF-8\nko_KR.UTF-8 UTF-8" >> /etc/locale.gen \
	&& locale-gen \
	&& ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
	&& bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# Install node packages
RUN npm install -g \
	typescript \
	nodemon
