# NOTE - A docker-compose.yml for PRODUCTION

version: "3.8"

# SECTION : SERVICES
services:
  app:
    image: app_prod_con:v1
    container_name: app_prod_con
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
     HOST: ${HOST:-localhost}
    env_file:
      - .env.production
    expose:
      - "3000"
    init: true
    networks:
      production:
        ipv4_address: 172.18.0.3
    ports:
      - "3000:3000"
    cpu_count: 8
    mem_limit: 16g

  database:
    image: db_prod_con:v1
    container_name: db_prod_con
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
     HOST: ${HOST:-localhost}
    env_file:
      - .env.production
    expose:
      - "5432"
    init: true
    networks:
      production:
        ipv4_address: 172.18.0.2
    volumes:
      # Database Volume
      - pgdata_prod:/var/lib/postgresql/data/

# SECTION : NETWORKS
networks:
  production:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  pgdata_prod:
# SECTION : VOLUMES
# volumes:
