# NOTE - A docker-compose.dev.yml for DEVELOPMENT

version: "3.8"

name: "ft_dev"

# SECTION : SERVICES
services:
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ./backend/.env
    expose:
      - "3000"
    networks:
      development:
        ipv4_address: 172.18.0.2
    ports:
      - "3000:3000"
    tty: true
    user: "node"
    volumes:
      - ./backend/:/workspaces/backend/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ./frontend/.env
    networks:
      development:
        ipv4_address: 172.18.0.3
    ports:
      - "4242:4242"
    tty: true
    user: "node"
    volumes:
      - ./frontend/:/workspaces/frontend/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

  database_dev:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    configs:
      - source: postgresql
        target: /var/lib/postgresql/data/postgresql.conf
    env_file:
      - ./database/.env
    expose:
      - "5432"
    networks:
      development:
        ipv4_address: 172.18.0.4
    tty: true
    volumes:
      - ./database/:/workspaces/database/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

# SECTION : NETWORKS
networks:
  development:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

# SECTION : CONFIGS
configs:
  postgresql:
    file: ./database/postgresql.conf

# SECTION : VOLUMES
# volumes:
