# NOTE - A docker-compose.dev.yml for DEVELOPMENT

version: "3.8"

# SECTION : SERVICES
services:
  backend_dev:
    container_name: back_dev_con
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    init: true
    entrypoint: [ sleep, infinity ]
    env_file:
      - ./backend/.env
    expose:
      - "3000"
    networks:
      development:
        ipv4_address: 172.18.0.2
    ports:
      - "3000:3000"
    volumes:
      - ./:/workspaces/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

  frontend_dev:
    container_name: front_dev_con
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    init: true
    entrypoint: [ sleep, infinity ]
    env_file:
      - ./frontend/.env
    networks:
      development:
        ipv4_address: 172.18.0.3
    ports:
      - "4242:4242"
    volumes:
      - ./:/workspaces/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

  database_dev:
    container_name: db_dev_con
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    init: true
    entrypoint: [ sleep, infinity ]
    env_file:
      - ./database/.env

    expose:
      - "5432"
    networks:
      development:
        ipv4_address: 172.18.0.4
    volumes:
      - ./:/workspaces/:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Config files
      - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - pgdata:/var/lib/postgresql/data/

# SECTION : NETWORKS
networks:
  development:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${PGDATA_DIR}
      o: bind

# SECTION : VOLUMES
# volumes:
