name: Feature Request (backend)
description: 백엔드 새로운 기능 추가
title: ":sparkles: "
labels: ["enhancement", "backend"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 내용
      description: 추가하고자 하는 기능에 대하여 설명해주세요.
      value: |
        - 
    validations:
      required: true
