name: Feature Request
description: new feature request
title: ":sparkles: "
labels: ["enhancement"]
assignees:
  - 
body:
  - type: textarea
    id: feature
    attributes:
      label: What feature?
      description: Describe the feature you want to add
      value: |
        **내용**
        - 

    validations:
      required: true
