# NOTE : A Dockerfile is for DATABASE DEVELOPMENT environment

FROM postgres:15.1-bullseye

# Install useful tools
RUN apt-get update && apt-get install -y \
	curl \
	git \
	htop \
	iproute2 \
	less \
	man-db \
	manpages-dev \
	net-tools \
	procps \
	tree \
	vim \
	locales \
	&& echo "set nu\nsyntax on\nset mouse=a\nset shiftwidth=4\nset tabstop=4\nset enc=utf-8" > /root/.vimrc

# Set locales, timezone & Install oh-my-bash
RUN echo "en_US.UTF-8 UTF-8\nko_KR.UTF-8 UTF-8" >> /etc/locale.gen \
	&& locale-gen \
	&& ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
	&& bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

COPY ./docker-entrypoint.dev.sh /tmp/entrypoint.sh

ENTRYPOINT [ "/tmp/entrypoint.sh" ]

CMD [ "sleep", "infinity" ]

HEALTHCHECK --interval=5s --start-period=10s --retries=5 CMD pg_isready -d dev || exit 1
